version: "3.8" # Updated to the latest version
services:
  db:
    image: mysql:latest
    container_name:  "db-postgres"
    environment:
      - TZ=Asia/Seoul
    env_file:
      - ./.env
    ports:
      - "3306:3306"
    networks:
      - default
    aliases:
      - db-postgres
  back:
    container_name: "back-nestjs"
    env_file:
     - ./.env
    ports:
      - "5000:5000"
    build:
      context: .
      dockerfile: Dockerfile.back
    depends_on:
      - db
    networks:
      - default
    aliases:
      - back-nestjs
    restart: unless-stopped
  front:
    container_name: "front-nextjs"
    build:
      context: .
      dockerfile: Dockerfile.front
    env_file:
     - ./.env
    ports:
      - "3000:3000"
    networks:
      - default
    aliases:
      - front-nextjs

networks:
  default:
