version: "3.8" # Updated to the latest version
services:
  db:
    image: mysql:latest
    container_name:  "db-mysql"
    environment:
      - TZ=Asia/Seoul
    env_file:
      - ./.env
    ports:
      - "3306:3306"
    networks:
      - default
  back:
    container_name: "back-nestjs"
    env_file:
     - ./.env
    ports:
      - "${BACK_PORT}:3005"
    build:
      context: .
      dockerfile: Dockerfile.back
    depends_on:
      - db
    networks:
      - default
    restart: unless-stopped
  front:
    container_name: "front-nuxt"
    build:
      context: .
      dockerfile: Dockerfile.front
    env_file:
     - ./.env
    ports:
      - "${FRONT_PORT}:3000"
    networks:
      - default
networks:
  default:
